contrataqui/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("site_final.urls")),
    path("usuarios/", include("django.contrib.auth.urls")),
    path("usuarios/", include("usuarios_site.urls")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

site_final/urls.py
from django import views
from django.urls import path, include
from .views import HomeView, ServicoDetailView,CategoriaDetailView,CategoriaListView,SubCategoriaDetailView,SubCategoriaListView,ServicoCreateView,ServicoDeleteView,ServicoListView,ServicoUpdateView,SearchView
from . import views

urlpatterns = [
    path('',HomeView.as_view(),name="home"),
    path('categorias/', CategoriaListView.as_view(), name='categoria_list'),
    path('categorias/<slug:slug>/', CategoriaDetailView.as_view(), name='categoria_detail'),
    path('categorias/<slug:categoria_slug>/', SubCategoriaListView.as_view(), name='subcategoria_list'),
    path('categorias/<slug:categoria_slug>/<slug:subcategoria_slug>/', SubCategoriaDetailView.as_view(), name='subcategoria_detail'),
    path('criar/', ServicoCreateView.as_view(), name='servico-create'),
    path('lista/', ServicoListView.as_view(), name='servico-list'),
    path('<int:pk>/editar/', ServicoUpdateView.as_view(), name='servico-update'),
    path('<int:pk>/deletar/', ServicoDeleteView.as_view(), name='servico-delete'),
    path('servico/<int:pk>/', ServicoDetailView.as_view(), name='servico-detail'),
    path('ajax_select/', include('ajax_select.urls')),
    path('get_subcategorias/', views.get_subcategorias, name='get_subcategorias'),
    path('buscando/', SearchView, name = "search"),
    path('servico/<int:servico_id>/mensagens/<str:username>/<str:autor_username>/', views.conversas, name='conversas'),
    path('<str:username>/lista_conversas/', views.servico_lista_conversas, name='servico_lista_conversas'),
    path('servico/<int:servico_id>/proposta/criar/<str:username>/<str:autor_username>/', views.criar_proposta, name='criar_proposta'),
    path('servico/<int:servico_id>/proposta/listar/', views.listar_propostas, name='listar_propostas'),
    path('servico/<int:servico_id>/proposta/<int:proposta_id>/', views.detalhe_proposta, name='proposta_detail'),
    path('proposta/<int:proposta_id>/aceitar/', views.aceitar_proposta, name='aceitar_proposta'),
    path('proposta/<int:proposta_id>/recusar/', views.recusar_proposta, name='recusar_proposta'),
    path('perfil/<int:perfil_id>/avaliacao/', views.criar_avaliacao, name='criar_avaliacao'),
    path('detalhe_proposta_aceita/<int:proposta_aceita_id>/', views.detalhe_proposta_aceita, name='detalhe_proposta_aceita'),
    path('finalizar_proposta_aceita/<int:proposta_aceita_id>/', views.finalizar_proposta_aceita, name='finalizar_proposta_aceita'),

]

site_final/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify


class Categoria(models.Model):
    nome = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, blank=True)


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.nome).title()

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('categoria_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.nome


class SubCategoria(models.Model):
    categoria_pai = models.ForeignKey(Categoria, related_name='subcategorias', on_delete=models.CASCADE)
    nome = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.nome)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('subcategoria_detail', kwargs={'categoria_slug': self.categoria_pai.slug, 'subcategoria_slug': self.slug})

    def __str__(self):
        return self.nome
    
    def __str__(self):
        return self.nome + " | Categoria: " + str(self.categoria_pai)

class Servico(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField()
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    subcategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)
    preco = models.DecimalField(max_digits=6, decimal_places=2, default=0.0)

    def __str__(self):
        return self.nome + " | SubCategoria: " + str(self.subcategoria)
    
class DiaDaSemana(models.Model):
    DIAS_DA_SEMANA = [
        ('Segunda', 'Segunda'),
        ('Terça', 'Terça'),
        ('Quarta', 'Quarta'),
        ('Quinta', 'Quinta'),
        ('Sexta', 'Sexta'),
        ('Sábado', 'Sábado'),
        ('Domingo', 'Domingo'),
    ]
    dia = models.CharField(max_length=50, choices=DIAS_DA_SEMANA)

    def __str__(self):
        return self.dia

class Perfil(models.Model):
    user = models.OneToOneField(User,null=True,on_delete=models.CASCADE)
    bio = models.TextField()
    foto_de_perfil = models.ImageField(null=True, blank=True,upload_to="imagens/perfil/")
    telefone = models.CharField(null=True, blank=True,max_length=11)
    whatsapp = models.CharField(null=True, blank=True,max_length=11)
    instagram = models.CharField(null=True, blank=True,max_length=25)
    dias_de_trabalho = models.ManyToManyField(DiaDaSemana)
    horario_entrada = models.TimeField(default='09:00')
    horario_saida = models.TimeField(default='18:00')
    nota_media = models.DecimalField(max_digits=3, decimal_places=2, default=0.0)
    numero_avaliacoes = models.IntegerField(default=0)

    
class SalaDeMensagens(models.Model):
    servico = models.ForeignKey('Servico', on_delete=models.CASCADE)
    clientes = models.ManyToManyField(User, related_name='salas_de_mensagens')
    identificador_sala = models.CharField(max_length=100, default='seila')

    def __str__(self):
        return f"Sala de Mensagens para {self.servico.nome}"

class Mensagem(models.Model):
    sala_de_mensagens = models.ForeignKey(SalaDeMensagens, on_delete=models.CASCADE)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    texto = models.TextField()
    data_envio = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Mensagem de {self.autor.username} para {self.sala_de_mensagens.servico.nome}"

class Notificacao(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    sala_de_mensagens = models.ForeignKey(SalaDeMensagens, on_delete=models.CASCADE)
    visualizada = models.BooleanField(default=False)
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Notificação para {self.usuario.username}"
    
class PropostaServico(models.Model):
    servico = models.ForeignKey(Servico, on_delete=models.CASCADE)
    autor = models.ForeignKey(User, related_name='propostas_feitas', on_delete=models.CASCADE)
    cliente = models.ForeignKey(User, related_name='propostas_recebidas', on_delete=models.CASCADE)
    valor_proposta = models.DecimalField(max_digits=10, decimal_places=2)
    aceita = models.BooleanField(null=True, blank=True)
    recusada = models.BooleanField(null=True, blank=True)

    def __str__(self):
        return f"Proposta de {self.autor.username} para {self.servico.nome}"
    



class Avaliacao(models.Model):
    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE, related_name='avaliacoes')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    nota = models.IntegerField()

class PropostaAceita(models.Model):
    proposta = models.OneToOneField(PropostaServico, on_delete=models.CASCADE, related_name='proposta_aceita')
    concluida = models.BooleanField(default=False)

    def __str__(self):
        return f"Proposta aceita para {self.proposta.servico.nome}"

site_final/forms.py
from django import forms
from .models import Servico
from ajax_select.fields import AutoCompleteSelectField



class ServicoForm(forms.ModelForm):
    subcategoria = AutoCompleteSelectField('subcategoria', required=False)

    class Meta:
        model = Servico
        fields = ['nome', 'descricao', 'categoria', 'subcategoria', 'preco']
        labels = {
            'nome': 'Nome do Serviço',
            'descricao': 'Descrição do Serviço',
            'categoria': 'Categoria do Serviço',
            'subcategoria': 'Subcategoria do Serviço',
            'preco': 'Preço do Serviço',
        }
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Insira aqui o nome do serviço'}),
            'descricao': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Insira aqui a descrição do serviço'}),
            'categoria': forms.Select(attrs={'class': 'form-control'}),
            'subcategoria': forms.Select(attrs={'class': 'form-control'}),
            'preco': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Insira aqui o preço do serviço'}),
        }

class ServicoUpdateForm(forms.ModelForm):
    class Meta:
        model = Servico
        fields = ['nome', 'descricao', 'categoria', 'subcategoria', 'preco']
        labels = {
            'nome': 'Nome do Serviço',
            'descricao': 'Descrição do Serviço',
            'categoria': 'Categoria do Serviço',
            'subcategoria': 'Subcategoria do Serviço',
            'preco': 'Preço do Serviço',
        }
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Insira aqui o nome do serviço'}),
            'descricao': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Insira aqui a descrição do serviço'}),
            'categoria': forms.Select(attrs={'class': 'form-control'}),
            'subcategoria': forms.Select(attrs={'class': 'form-control'}),
            'preco': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Insira aqui o preço do serviço'}),
        }


site_final/templates/servico/criar_proposta.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ContratAqui</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
        <h1>Criar Proposta para: {{ servico.nome }}</h1>

        <form action="{% url 'criar_proposta' servico_id=servico.id username=cliente.username autor_username=servico.autor.username %}" method="post">
            {% csrf_token %}
            <input type="number" name="valor_proposta" step="0.01" placeholder="Valor da Proposta" required><br>
            <button type="submit">Enviar Proposta</button>
        </form>
    {% endblock %}
</body>
</html>

site_final/templates/servico/detalhe_proposta.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ContratAqui</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
    <h2>Detalhes da Proposta</h2>
    <p>Proposta de: {{ proposta.autor.username }}</p>
    <p>Valor da Proposta: {{ proposta.valor_proposta }}</p>
    
    {% if is_cliente %}
        <a href="{% url 'aceitar_proposta' proposta_id=proposta.id %}">Aceitar</a>
        <a href="{% url 'recusar_proposta' proposta_id=proposta.id %}">Recusar</a>
    {% endif %}
    {% endblock %}
</body>
</html>

site_final/templates/servico/detalhe_proposta_aceita.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ContratAqui</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
    <h2>Detalhes da Proposta</h2>
    <p>Proposta de: {{ proposta_aceita.proposta.autor.username }}</p>
    <p>Valor da Proposta: {{ proposta_aceita.proposta.valor_proposta }}</p>

    <!-- Mostrar botão apenas para o cliente -->
    {% if is_cliente %}
        <form action="{% url 'finalizar_proposta_aceita' proposta_aceita.id %}">
            {% csrf_token %}
            <input type="submit" value="Serviço foi finalizado">
        </form>
    {% endif %}

    <!-- Botão para voltar para servico_lista_conversas -->
    <a href="{% url 'servico_lista_conversas' username=request.user.username %}">Voltar para lista de conversas</a>

    <!-- Adicione mais detalhes da proposta aceita, se necessário -->
    {% endblock %}
</body>
</html>

site_final/templates/servico/finalizar_proposta_aceita.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ContratAqui</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
    <h1>Finalizar Proposta</h1>
    <p>Tem certeza de que deseja marcar esta proposta como concluída?</p>

    <form action="{% url 'finalizar_proposta_aceita' proposta_aceita.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Marcar como concluída">
    </form>
    <a href="{% url 'servico_lista_conversas' username=request.user.username %}">Voltar para lista de conversas</a>
    {% endblock %}
</body>
</html>

site_final/templates/servico/listar_propostas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ContratAqui</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
        <h1>Propostas para o serviço "{{ servico.nome }}"</h1>
    
        {% if propostas %}
            <ul>
                {% for proposta in propostas %}
                    {% if not proposta.proposta_aceita %}
                        <li>
                            {% if request.user == servico.autor %}
                                Nome do Serviço: {{ proposta.servico.nome }} <br>
                                Nome do Cliente: {{ proposta.cliente.username }} <br>
                                Valor: R$ {{ proposta.valor_proposta }}
                                <a href="{% url 'proposta_detail' servico_id=servico.id proposta_id=proposta.pk %}">Ver proposta</a>
                            {% else %}
                                Nome do Serviço: {{ proposta.servico.nome }} <br>
                                Nome do Autor da Proposta: {{ proposta.autor.username }} <br>
                                Valor: R$ {{ proposta.valor_proposta }}
                                <a href="{% url 'proposta_detail' servico_id=servico.id proposta_id=proposta.pk %}">Ver proposta</a>
                            {% endif %}
                        </li>
                    {% endif %}
                {% empty %}
                    <li>Nenhuma proposta encontrada.</li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Sem propostas para esse serviço no momento.</p>
        {% endif %}
    {% endblock %}
</body>
</html>

site_final/templates/servico/servico_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ContratAqui</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
        <h1>Tem certeza que deseja excluir "{{ servico.nome }}"?</h1>
    
        <form method="post">
            {% csrf_token %}
            <button type="submit" name="confirm" value="yes">Sim</button>
            <a href="{% url 'servico-detail' pk=servico.pk %}"><button type="button">Não</button></a>
        </form>
    {% endblock %}
</body>
</html>

site_final/templates/servico/servico_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
  <style>
    .flex-container {
      display: flex;
      justify-content: space-between;
    }
    .right-align {
      text-align: right;
    }
    </style>
    
    
</head>

<body>
  {% extends 'base.html' %}
  {% block content %}
  <h1>{{ servico.nome }}</h1>

  <p><strong>Serviço Prestado:</strong> {{ servico.nome }}</p>
  <p><strong>Prestador de Serviço:</strong> {{ servico.autor.first_name }} {{ servico.autor.last_name }}</p>
  <p><strong>Descrição:</strong> {{ servico.descricao }}</p>
  <p><strong>Preço:</strong> R${{ servico.preco }}</p>

  {% if user.is_authenticated %}
    {% if user != servico.autor %}
      <form action="{% url 'conversas' servico_id=servico.id username=request.user.username autor_username=servico.autor.username %}" method="post">
        {% csrf_token %}
        <button type="submit">ContratAqui</button>
      </form>'
    {% else %}
      <a href="{% url 'servico-update' pk=servico.pk %}" class="btn btn-primary">Editar</a>
      <form action="{% url 'servico-delete' pk=servico.pk %}" method="post" style="display: inline;">
        {% csrf_token %}
        <input type="hidden" name="action" value="delete">
        <button type="submit" class="btn btn-danger">Excluir</button>
      </form>
  {% endif %}
  {% endif %}

  <br><br><br>
  <div class="card mb-3">
    <div class="row g-0">
      <div class="col-md-2">
        <img src="{{servico.autor.perfil.foto_de_perfil.url}}" class="img-fluid rounded-start">
      </div>
      <div class="col-md-10">
        <div class="card-body">
          <div class="flex-container">
            <h5 class="card-title">Prestador: {{ servico.autor.first_name }} {{ servico.autor.last_name }}</h5>
            <div class="right-align">
              <h6><strong>Nota:</strong>{{servico.autor.perfil.nota_media}}</h6>
              <h6><strong>Serviços Prestados:</strong>{{servico.autor.perfil.numero_avaliacoes}}</h6>
            </div>
          </div>
          {% if servico.autor.perfil.telefone %}
          <span class="card-text"><small
              class="text-body-secondary"><strong>Telefone:</strong> {{servico.autor.perfil.telefone}} </small></span>
          {% endif %}

          {% if servico.autor.perfil.whatsapp %}
          <span class="card-text"><small
              class="text-body-secondary"><strong>Whatsapp:</strong> {{servico.autor.perfil.whatsapp}} </small></span>
          {% endif %}

          {% if servico.autor.perfil.instagram %}
          <span class="card-text"><small
              class="text-body-secondary"><strong>Instagram:</strong> {{servico.autor.perfil.instagram}} </small></span>
          {% endif %}

          {% if servico.autor.perfil.bio %}
          <p class="card-text"><strong>Bio:</strong> {{ servico.autor.perfil.bio }}</p>
          {% endif %}

          {% if servico.autor.perfil.dias_de_trabalho %}
          <span class="card-text"><small
            class="text-body-secondary"><strong>Dias de Trabalho:</strong>
          {% for dia in servico.autor.perfil.dias_de_trabalho.all %}
           {{ dia }} |
          {% endfor %}</small></span>
          {% endif %}

          {% if servico.autor.perfil.horario_entrada %}
          <span class="card-text"><small
            class="text-body-secondary"><strong>Horário de Entrada:</strong> {{ servico.autor.perfil.horario_entrada|time:"H:i" }}</small></span>
          {% endif %}

          {% if servico.autor.perfil.horario_saida %}
          <span class="card-text"><small
            class="text-body-secondary"><strong>Horário de Saída:</strong> {{ servico.autor.perfil.horario_saida|time:"H:i" }}</small></span>
          {% endif %}

        </div>
      </div>
    </div>
  </div>
  {% endblock %}
</body>

</html>

site_final/templates/servico/servico_editar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ContratAqui</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function(){
            $('#id_categoria').change(function(){
                var categoriaId = $(this).val();
                if (categoriaId) {
                    $.ajax({
                        url: '/get_subcategorias/',
                        type: 'GET',
                        data: {'categoria_id': categoriaId},
                        success: function(data){
                            $('#id_subcategoria').html(data.options);
                        }
                    });
                } else {
                    $('#id_subcategoria').empty();
                }
            });
        });
    </script>    
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}

    <h1>Editar Serviço: {{ servico.nome }}</h1>
        <form method="post">
            {% csrf_token %}
            Nome do Serviço :{{ form.nome }}
            <br>
            <br>
            Descrição do serviço: {{ form.descricao }}
            <br>
            <br>
            Preço do Serviço: R${{ form.preco }}
            <br>
            <br>
            <!-- Campo de Categoria -->
            <label for="id_categoria">Categoria:</label>
            {{ form.categoria }}
            <br>
            <br>
            <br>
            <!-- Campo de Subcategoria -->
            <label for="id_subcategoria">Subcategoria:</label>
            <select name="subcategoria" id="id_subcategoria">
                <!-- As opções de subcategorias serão preenchidas dinamicamente pelo JavaScript -->
            </select>
            <br>
            <br>
            <button type="submit">Salvar Serviço</button>
        </form>
    {% endblock %}
</body>
</html>

site_final/templates/servico/servico_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ContratAqui</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function(){
            $('#id_categoria').change(function(){
                var categoriaId = $(this).val();
                if (categoriaId) {
                    $.ajax({
                        url: '/get_subcategorias/',
                        type: 'GET',
                        data: {'categoria_id': categoriaId},
                        success: function(data){
                            $('#id_subcategoria').html(data.options);
                        }
                    });
                } else {
                    $('#id_subcategoria').empty();
                }
            });
        });
    </script>    
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}

        <h1>Adicionar Novo Serviço</h1>
        <form method="post">
            {% csrf_token %}
            Nome do Serviço :{{ form.nome }}
            <br>
            <br>
            Descrição do serviço: {{ form.descricao }}
            <br>
            <br>
            Preço do Serviço: R${{ form.preco }}
            <br>
            <br>
            <!-- Campo de Categoria -->
            <label for="id_categoria">Categoria:</label>
            {{ form.categoria }}
            <br>
            <br>
            <br>
            <!-- Campo de Subcategoria -->
            <label for="id_subcategoria">Subcategoria:</label>
            <select name="subcategoria" id="id_subcategoria">
                <!-- As opções de subcategorias serão preenchidas dinamicamente pelo JavaScript -->
            </select>
            <br>
            <br>
            <button type="submit">Salvar Serviço</button>
        </form>
    {% endblock %}
</body>
</html>

site_final/templates/servico/servico_lista_conversas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ContratAqui</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
    <h1>Lista de Conversas para {{ usuario.username }}</h1>

    <h2>Conversas em que você é o autor:</h2>
    <ul>
        {% for sala in salas_autor %}
        <li>
            {{ sala.servico.nome }} -
            {% for cliente in sala.clientes.all %}
                {% if cliente != usuario %}
                Cliente: {{ cliente.username }}
                <form action="{% url 'conversas' sala.servico.pk cliente.username sala.servico.autor.username %}">
                    <button type="submit">Abrir Conversa</button>
                </form>
                {% endif %}
            {% endfor %}
            
            <!-- Adicionando botão para listar propostas -->
            <form action="{% url 'listar_propostas' sala.servico.pk %}">
                <button type="submit">Listar Propostas</button>
                {% for proposta_aceita in propostas_aceitas %}
                    {% if proposta_aceita.proposta.servico == sala.servico and proposta_aceita.proposta.autor == sala.servico.autor and proposta_aceita.proposta.cliente != usuario %}
                        <!-- Verifica se a condição acima identifica corretamente a proposta aceita -->
                        <form action="{% url 'detalhe_proposta_aceita' proposta_aceita.id %}">
                            <button type="submit">Serviço em andamento</button>
                        </form>
                    {% endif %}
                {% endfor %}
                
                <!-- Frase "Serviço finalizado" para o autor -->
                {% for proposta_aceita_finalizada in propostas_aceitas_finalizadas_autor %}
                    {% if proposta_aceita_finalizada.proposta.servico == sala.servico and proposta_aceita_finalizada.proposta.autor == sala.servico.autor %}
                        <p>Serviço finalizado</p>
                    {% endif %}
                {% endfor %}
            </form>
        </li>
        {% endfor %}
    </ul>

    <h2>Conversas em que você é o cliente:</h2>
    <ul>
        {% for sala in salas_cliente %}
        <li>
            <form action="{% url 'conversas' sala.servico.pk usuario.username sala.servico.autor.username %}">
                <button type="submit">{{ sala.servico.nome }} - Autor do Serviço: {{ sala.servico.autor.username }}</button>
            </form>
            <!-- Adicionando botão para listar propostas -->
            <form action="{% url 'listar_propostas' sala.servico.pk %}">
                <button type="submit">Listar Propostas</button>
                
                <!-- Botão "Serviço em andamento" para o cliente -->
                {% for proposta_aceita in propostas_aceitas %}
                    {% if proposta_aceita.proposta.servico == sala.servico and proposta_aceita.proposta.cliente == cliente and proposta_aceita.proposta.autor == sala.servico.autor %}
                        <!-- Verificar se a condição acima está identificando corretamente a proposta aceita -->
                        <form action="{% url 'detalhe_proposta_aceita' proposta_aceita.id %}">
                            <button type="submit">Serviço em andamento</button>
                        </form>
                    {% endif %}
                {% endfor %}
                <!-- Frase "Serviço finalizado" para o cliente -->
                {% for proposta_aceita_finalizada in propostas_aceitas_finalizadas_cliente %}
                    {% if proposta_aceita_finalizada.proposta.servico == sala.servico and proposta_aceita_finalizada.proposta.cliente == usuario and proposta_aceita_finalizada.proposta.autor != usuario %}
                        <p>Serviço finalizado</p>
                    {% endif %}
                {% endfor %}
            </form>
        </li>
        {% endfor %}
    </ul>
    {% endblock %}
</body>
</html>

site_final/templates/servico/servico_mensagens.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- ... -->
  <style>
    .message-container {
      display: flex;
      flex-direction: column;
    }

    .message {
      margin-bottom: 10px;
      padding: 8px;
      border-radius: 5px;
      max-width: 70%;
    }

    .message.author {
      align-self: flex-start;
      background-color: #d3d3d3;
    }

    .message.client {
      align-self: flex-end;
      background-color: #a2e8d8;
    }
  </style>
</head>

<body>
  {% extends 'base.html' %}
  {% block content %}
  <h1>Troca de Mensagens para: {{ servico.nome }}</h1>

  <div class="message-container">
    <!-- Exibir as mensagens existentes -->
    {% if mensagens %}
      {% for mensagem in mensagens %}
        <div class="message {% if mensagem.autor == servico.autor %}author{% else %}client{% endif %}">
          <strong>{{ mensagem.autor.username }}:</strong> {{ mensagem.texto }}
        </div>
      {% endfor %}
    {% else %}
      <p>Nenhuma mensagem ainda. Seja o primeiro a enviar uma mensagem!</p>
    {% endif %}
  </div>

  <!-- Formulário para enviar mensagens -->
  <form action="{% url 'conversas' servico_id=servico.id username=cliente.username autor_username=servico.autor.username %}" method="post">
    {% csrf_token %}
    <textarea name="texto_mensagem" rows="4" cols="50"></textarea><br>
    <button type="submit">Enviar Mensagem</button>
  </form>


  {% if user == servico.autor %}
    <a href="{% url 'criar_proposta' servico_id=servico.id username=cliente.username autor_username=servico.autor.username %}">Criar Proposta</a>
  {% endif %}
  {% if user == cliente %}
    {% if proposta_criada %}
      <a href="{% url 'listar_propostas' servico_id=servico.id %}">Ver Propostas</a>
    {% else %}
      <p>Ainda não foi criada uma proposta para este serviço.</p>
    {% endif %}
  {% endif %}

  {% endblock %}
</body>
</html>